# Generated by Django 3.2.3 on 2021-09-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotisation', '0016_remove_saison_saison_prochaine'),
        ('inscription', '0026_alter_adherent_taille'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandesDobok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voeu_commande', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Commande de dobok')),
                ('tarif_info', models.IntegerField(verbose_name='Tarif informatif')),
                ('statut_distribution', models.CharField(blank=True, choices=[('0', 'Non distribué'), ('1', 'Distribué')], default=0, max_length=1, null=True, verbose_name='Distribution')),
                ('date_distribution', models.DateField(blank=True, null=True, verbose_name='Date distribution')),
                ('statut_paiement', models.CharField(blank=True, choices=[('0', 'Non réglé'), ('1', 'Réglé')], default=0, max_length=1, null=True, verbose_name='Réglement')),
                ('montant_reel', models.IntegerField(blank=True, null=True, verbose_name='Montant réglé')),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('date_last_modif', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.adherent')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.famille')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.saison')),
            ],
        ),
    ]
