# Generated by Django 3.2.3 on 2021-09-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandesdobok',
            name='taille',
            field=models.IntegerField(default=100, verbose_name='Taille'),
        ),
        migrations.AlterField(
            model_name='commandesdobok',
            name='tarif_info',
            field=models.IntegerField(verbose_name='Tarif (info)'),
        ),
        migrations.AlterField(
            model_name='commandesdobok',
            name='voeu_commande',
            field=models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Voeu dobok'),
        ),
    ]
