# Generated by Django 3.2.3 on 2021-09-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_commandesdobok_taille'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixDobok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille_min', models.IntegerField(verbose_name='Taille mini en cm')),
                ('taille_max', models.IntegerField(verbose_name='Taille maxi en cm')),
                ('prix', models.IntegerField(verbose_name='Prix')),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('date_last_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='commandesdobok',
            name='taille',
            field=models.IntegerField(verbose_name='Taille (cm)'),
        ),
    ]
