# Generated by Django 3.2.3 on 2021-09-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_auto_20210927_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixdobok',
            name='prix',
            field=models.CharField(max_length=2, verbose_name='Prix'),
        ),
    ]
