# Generated by Django 3.2.3 on 2021-09-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0006_alter_prixdobok_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandesdobok',
            name='tarif_info',
            field=models.CharField(max_length=12, verbose_name='Tarif (info)'),
        ),
        migrations.AlterField(
            model_name='prixdobok',
            name='prix',
            field=models.IntegerField(verbose_name='Prix'),
        ),
    ]
