# Generated by Django 3.2.3 on 2022-06-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0009_auto_20210927_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandesdobok',
            name='statut_commande',
            field=models.CharField(choices=[('1', 'En cours'), ('2', 'Distribuée'), ('3', 'Annulée')], default=1, max_length=1, verbose_name='Commande'),
        ),
    ]
