# Generated by Django 3.2.3 on 2021-05-20 16:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_catg', models.CharField(max_length=15, verbose_name='Catégorie')),
                ('age_inf_catg', models.IntegerField(validators=[django.core.validators.MinValueValidator(3)], verbose_name='Age plancher')),
                ('age_sup_catg', models.IntegerField(blank=True, null=True, verbose_name='Age plafond')),
                ('ordre_affichage', models.IntegerField(blank=True, verbose_name="Ordre d'affichage")),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_discipl', models.CharField(max_length=20, verbose_name='Discipline')),
                ('ordre_affichage', models.IntegerField(blank=True, verbose_name="Ordre d'affichage")),
            ],
        ),
        migrations.CreateModel(
            name='MotifReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_reduc', models.CharField(max_length=50, verbose_name='Motif réduction')),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saison', models.CharField(max_length=12, verbose_name='Saison')),
            ],
        ),
        migrations.CreateModel(
            name='TauxReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_reduc', models.IntegerField(verbose_name='Réduction en %')),
                ('nom_reduc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.motifreduction')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.saison')),
            ],
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tarif', models.CharField(max_length=20, verbose_name='Code Tarification')),
                ('tarif_nouveau', models.IntegerField(blank=True, null=True, verbose_name='Tarif nouvel adhérent')),
                ('tarif_ancien', models.IntegerField(blank=True, null=True, verbose_name='Tarif ancien adhérent')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.categorie')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.discipline')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.saison')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.saison'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='saison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.saison'),
        ),
    ]
