# Generated by Django 3.2.3 on 2021-05-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tauxreduction',
            name='condition_anciennete',
            field=models.BooleanField(default=False, verbose_name='Réservé aux anciens adhérents?'),
        ),
    ]
