# Generated by Django 3.2.3 on 2021-05-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0002_tauxreduction_condition_anciennete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tauxreduction',
            name='condition_anciennete',
            field=models.BooleanField(default=False, verbose_name='Réservé aux anciens adhérents'),
        ),
    ]
