# Generated by Django 3.2.3 on 2021-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0003_alter_tauxreduction_condition_anciennete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tauxreduction',
            name='condition_anciennete',
        ),
        migrations.AddField(
            model_name='tauxreduction',
            name='condition_anciens',
            field=models.BooleanField(default=False, verbose_name='Applicable aux anciens adhérents'),
        ),
        migrations.AddField(
            model_name='tauxreduction',
            name='condition_nouveaux',
            field=models.BooleanField(default=False, verbose_name='Applicable aux nouveaux adhérents'),
        ),
    ]
