# Generated by Django 3.2.3 on 2021-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0004_auto_20210521_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='motifreduction',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Code réduction'),
        ),
        migrations.AddField(
            model_name='motifreduction',
            name='condition_reduc',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Condition réduction'),
        ),
    ]
