# Generated by Django 3.2.3 on 2021-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0005_auto_20210521_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='tauxreduction',
            name='motif_reduc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Motif réduction'),
        ),
    ]
