# Generated by Django 3.2.3 on 2021-05-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0006_tauxreduction_motif_reduc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motifreduction',
            name='code',
        ),
        migrations.RemoveField(
            model_name='motifreduction',
            name='condition_reduc',
        ),
    ]
