# Generated by Django 3.2.3 on 2021-05-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0007_auto_20210521_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motifreduction',
            old_name='nom_reduc',
            new_name='modif_reduct',
        ),
        migrations.RenameField(
            model_name='tauxreduction',
            old_name='nom_reduc',
            new_name='modif_reduct',
        ),
        migrations.RenameField(
            model_name='tauxreduction',
            old_name='motif_reduc',
            new_name='nom_reduct',
        ),
    ]
