# Generated by Django 3.2.3 on 2021-05-21 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0008_auto_20210521_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motifreduction',
            old_name='modif_reduct',
            new_name='motif_reduct',
        ),
        migrations.RemoveField(
            model_name='tauxreduction',
            name='modif_reduct',
        ),
        migrations.AddField(
            model_name='tauxreduction',
            name='motif_reduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cotisation.motifreduction', verbose_name='Motif réduction'),
        ),
        migrations.AlterField(
            model_name='tauxreduction',
            name='nom_reduct',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom réduction'),
        ),
    ]
