# Generated by Django 3.2.3 on 2021-05-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0011_saison_saison_actuelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='etudiant',
            field=models.BooleanField(default=0),
        ),
    ]
