# Generated by Django 3.2.3 on 2021-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0012_categorie_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='code_catg',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code catégorie'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='code_discipl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code discipline'),
        ),
    ]
