# Generated by Django 3.2.3 on 2021-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0014_auto_20210529_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='saison',
            name='saison_prochaine',
            field=models.BooleanField(default=False),
        ),
    ]
