# Generated by Django 3.2.3 on 2021-07-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0015_saison_saison_prochaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saison',
            name='saison_prochaine',
        ),
    ]
