# Generated by Django 3.2.3 on 2022-06-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotisation', '0018_auto_20220626_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_en_cours',
            field=models.BooleanField(default=False, verbose_name='Cocher la case pour passe en mode maintenance / Décocher pour retirer le mode maintenance'),
        ),
    ]
