# Generated by Django 3.2.3 on 2021-05-25 11:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotisation', '0010_tauxreduction_condition_reduc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_adh', models.CharField(max_length=50, verbose_name='Nom adhérent')),
                ('prenom_adh', models.CharField(max_length=50, verbose_name='Prénom adhérent')),
                ('ddn', models.DateField()),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=1)),
                ('adresse', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5, verbose_name='Code postal')),
                ('ville', models.CharField(max_length=35)),
                ('nationalite', models.CharField(max_length=40, verbose_name='Nationalité')),
                ('numtel_adh', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro téléphone')),
                ('email_adh', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('date_last_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategorieCombat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_catg_combat', models.CharField(max_length=50, verbose_name='Catégorie combat')),
                ('annee_debut', models.IntegerField(validators=[django.core.validators.MinValueValidator(2021)], verbose_name='Année validité catégorie combat')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_contact', models.CharField(max_length=50, verbose_name='Nom contact')),
                ('prenom_contact', models.CharField(max_length=50, verbose_name='Prénom contact')),
                ('numtel_contact1', models.CharField(max_length=10, verbose_name='Numéro téléphone 1')),
                ('numtel_contact2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro téléphone 2')),
                ('numtel_contact3', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro téléphone 3')),
                ('email_adh', models.CharField(max_length=100, verbose_name='E-mail')),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('date_last_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_famille', models.CharField(max_length=50, verbose_name='Nom de la famille')),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(max_length=20)),
                ('grade', models.IntegerField(blank=True, max_length=1, null=True)),
                ('barette', models.IntegerField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdhFamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.adherent')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.famille')),
            ],
        ),
        migrations.CreateModel(
            name='Adherent_Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certif_med', models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, verbose_name='Certificat médical')),
                ('photo', models.CharField(choices=[('0', 'Fournie'), ('1', 'Non fournie')], max_length=1)),
                ('date_crea', models.DateTimeField(auto_now_add=True)),
                ('date_last_modif', models.DateTimeField(auto_now=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.adherent')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.categorie')),
                ('categorie_combat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.categoriecombat')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.discipline')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.grade')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotisation.saison')),
            ],
        ),
        migrations.CreateModel(
            name='AdhContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.adherent')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.contact')),
            ],
        ),
    ]
