# Generated by Django 3.2.3 on 2021-05-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='keup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='barette',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
