# Generated by Django 3.2.3 on 2021-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_auto_20210525_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent_saison',
            name='certif_med',
            field=models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], default=0, max_length=1, verbose_name='Certificat médical'),
        ),
        migrations.AlterField(
            model_name='adherent_saison',
            name='photo',
            field=models.CharField(choices=[('0', 'Fournie'), ('1', 'Non fournie')], default=0, max_length=1),
        ),
    ]
