# Generated by Django 3.2.3 on 2021-05-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_auto_20210526_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_adh',
            new_name='email_contact',
        ),
    ]
