# Generated by Django 3.2.3 on 2021-05-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_rename_email_adh_contact_email_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='barette',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
    ]
