# Generated by Django 3.2.3 on 2021-05-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_auto_20210526_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriecombat',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='âge'),
        ),
    ]
