# Generated by Django 3.2.3 on 2021-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_categoriecombat_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriecombat',
            name='age_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='âge maximum'),
        ),
        migrations.AddField(
            model_name='categoriecombat',
            name='age_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='âge minimum'),
        ),
    ]
