# Generated by Django 3.2.3 on 2021-05-27 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_auto_20210527_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriecombat',
            name='age',
        ),
    ]
