# Generated by Django 3.2.3 on 2021-05-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0010_adherent_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='etudiant',
            field=models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], default=0, max_length=1),
        ),
    ]
