# Generated by Django 3.2.3 on 2021-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0012_auto_20210527_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent_saison',
            name='photo',
            field=models.CharField(choices=[('0', 'Non Fournie'), ('1', 'Fournie')], default=0, max_length=1),
        ),
    ]
