# Generated by Django 3.2.3 on 2021-05-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0013_alter_adherent_saison_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent_saison',
            name='certif_med',
            field=models.CharField(choices=[('0', 'Non Fourni'), ('1', 'Fourni')], default=0, max_length=1, verbose_name='Certificat médical'),
        ),
    ]
