# Generated by Django 3.2.3 on 2021-05-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0015_historiquepaiement_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepaiement',
            name='date_rglt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date règlement'),
        ),
    ]
