# Generated by Django 3.2.3 on 2021-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0016_alter_historiquepaiement_date_rglt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquepaiement',
            name='type_rglmt',
            field=models.CharField(blank=True, choices=[('C', 'Chèque'), ('L', 'Liquide'), ('V', 'Virement')], max_length=1, null=True, verbose_name='Type règlement'),
        ),
    ]
