# Generated by Django 3.2.3 on 2021-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0017_alter_historiquepaiement_type_rglmt'),
    ]

    operations = [
        migrations.AddField(
            model_name='adherent',
            name='taille',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='Taille en cm'),
        ),
    ]
