# Generated by Django 3.2.3 on 2021-05-29 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0018_adherent_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='taille',
            field=models.IntegerField(blank=True, max_length=3, null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Taille en cm'),
        ),
    ]
