# Generated by Django 3.2.3 on 2021-06-02 13:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0019_alter_adherent_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='etudiant',
            field=models.CharField(choices=[('0', 'Non'), ('1', 'Oui')], max_length=1),
        ),
        migrations.AlterField(
            model_name='adherent',
            name='taille',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Taille en cm'),
        ),
        migrations.AlterField(
            model_name='adherent_saison',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscription.grade'),
        ),
    ]
