# Generated by Django 3.2.3 on 2021-09-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0022_auto_20210704_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiquepaiement',
            name='date_rglt',
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='bank_chq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='date_depot_bank',
            field=models.DateField(blank=True, null=True, verbose_name='Date dépôt à banque'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='date_encaissement',
            field=models.DateField(blank=True, null=True, verbose_name='Date encaissement'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='date_recept_rglmt',
            field=models.DateField(blank=True, null=True, verbose_name='Date réception'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='date_saisie',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date saisie'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='encaisse',
            field=models.CharField(blank=True, choices=[('0', 'Non'), ('1', 'Oui')], max_length=1, null=True, verbose_name='Chèque encaissé'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='num_chq',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Numéro du chèque'),
        ),
        migrations.AddField(
            model_name='historiquepaiement',
            name='proprio_chq',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Propriétaire du chèque'),
        ),
    ]
