# Generated by Django 3.2.3 on 2021-09-05 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0024_auto_20210902_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='taille',
            field=models.IntegerField(default=200, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(210)], verbose_name='Taille en cm'),
            preserve_default=False,
        ),
    ]
