# Generated by Django 3.2.3 on 2021-09-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0025_alter_adherent_taille'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adherent',
            name='taille',
            field=models.IntegerField(verbose_name='Taille en cm'),
        ),
    ]
